---
date: last-modified
date-format: long
bibliography: bio.bib
csl: harvard-cite-them-right.csl
title: TNE^2 + I
execute:
  echo: false
  freeze: true
format:
  html:
    code-copy: true
    code-link: true
    toc: true
    toc-title: On this page
    toc-depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    mainfont: "Times New Roman"
    sansfont: "Arial"
    monofont: "Courier New"
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: false
    colorlinks: true
    highlight-style: github
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

::: {.callout-note!!!}
## Setup Instructions for Team!!!!
If you are running this locally (Windows/Mac) and see a "Font not found" error:
1. Please install **Spectral**, **Roboto Flex**, and **Liberation Mono** fonts manually.
2. OR, temporarily comment out the font settings in the YAML header above.
**Note:** This file will render perfectly in the John's Docker container as these fonts are pre-installed there.
:::

## Declaration of Authorship {.unnumbered .unlisted}

We, **"TNE^2 + I"**, pledge our honour that the work presented in this assessment is our own. Where information has been derived from other sources, we confirm that this has been indicated in the work. Where a Large Language Model such as ChatGPT has been used we confirm that we have made its contribution to the final submission clear.


Date: **{{< meta date >}}**

Student Numbers: 25198678, 25060351, 25153376, 25211516, 25127081

**Student Details:**
*   [**Nadia Jimena Cabrera Salazar** (ID: 25198678)](https://github.com/EmilyDeeb/0013_Assesment)
*   [**Emily Dugmore** (ID: 25060351)](https://github.com/EmilyDeeb)
*   [**Julissa Tabata Paredes Condor** (ID: 25153376)](https://github.com/EmilyDeeb)
*   [**Jiaying LI** (ID: 25211516)](https://github.com/EmilyDeeb)
*   [**Emily Deeb** (ID: 25127081)](https://github.com/EmilyDeeb)


## Priorities for Feedback

Are there any areas on which you would appreciate more detailed feedback if we're able to offer it?
General Knowlage of Coding, 
{{< pagebreak >}}


```{python}
import os
from urllib.request import urlretrieve

# --- 1. Setup URLs ---
# Using the raw links from our GitHub repository
bib_url = "https://raw.githubusercontent.com/JIAYING-ICE/0013_Assesment/main/bio.bib"
csl_url = "https://raw.githubusercontent.com/JIAYING-ICE/0013_Assesment/main/harvard-cite-them-right.csl"

# --- 2. Download Function ---
# Check if file exists, if not, download it.
def get_remote_file(file_name, url):
    if not os.path.exists(file_name):
        print(f"Downloading {file_name} from GitHub...")
        urlretrieve(url, file_name)
    else:
        print(f"{file_name} already exists.")

# --- 3. Execute ---
get_remote_file("bio.bib", bib_url)
get_remote_file("harvard-cite-them-right.csl", csl_url)
```


{{< pagebreak >}}

# Briefing



## References

(Parenthetical Citation)A: Most of the data comes from online sources [@insideairbnb].

(Narrative Citation)B: According to @insideairbnb, the data is open source.

Previous studies have confirmed this trend [@smith2021analysis; @doe2020airbnb].

Recent studies have questioned the accuracy of the data used in Airbnb research [@alsudaisIncorrectDataWidely2021].